blog/urls.py
# -*- coding: utf-8 -*-
import blog.views
from django.conf.urls import url

urlpatterns = [
    url(r'^$', blog.views.showBlog, {'template_name': 'blog/blog.html'},
        name='blog'),

    url(r'^(?P<row_slug>[-\w]+)/$', blog.views.showRow,
        {'template_name': 'blog/row.html'}, name='row_blog'),
]


main/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from main.views import mainPage
from main.views import download_price
from main.views import certificatesPage
from django.views.generic import TemplateView
from django.contrib.sitemaps.views import sitemap

from utilits.sitemap import productSitemap
from utilits.sitemap import categorySitemap
from utilits.sitemap import categoryClassSitemap
from utilits.sitemap import flatSitemap
from utilits.sitemap import ourWorksSitemap
from utilits.sitemap import certificateSitemap
from utilits.sitemap import blogSitemap

sitemaps = {'category': categorySitemap,
            'categoryClass': categoryClassSitemap,
            'product': productSitemap,
            'flatpages': flatSitemap,
            'ourworks': ourWorksSitemap,
            'certificate': certificateSitemap,
            'blog': blogSitemap,}

urlpatterns = [
    url(r'^download/$', download_price,
        name='download_price'),
    url(r'^$', mainPage, {'template_name': 'main.html'},
        name='main'),
    url(r'^certificate/$', certificatesPage, {'template_name': 'certificates/certificate.html'},
        name='certificate'),
    url(r'^robots.txt$', TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
        name="robots_file"),
    url(r'^sitemap.xml/$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
]

svet_vlad/urls.py
# -*- coding: utf-8 -*-
from django.contrib import admin
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static

urlpatterns = [
    url(r'^catalog/', include('catalog.urls')),
    url(r'^sender/', include('sender.urls')),
    url(r'^account/', include('account.urls')),
    url(r'^works/', include('ourwork.urls')),
    url(r'^blog/', include('blog.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('main.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
# -*- coding: utf-8 -*-
from django.db import models
from tinymce.models import HTMLField

class contactsModel(models.Model):
    defaultDict = {'name': u'ИП Зубов Владислав Сергеевич',
                   'street': u'160029, г.Вологда, ул.Прокатова, д.5, кв.111',
                   'inn': u'352601377742',
                   'bic': u'041909644',
                   'bicDecrpt': 'Отделение № 8638 Сбербанка России г.Вологда',
                   'rs': '40802810312000000863',
                   'ks': '30101810900000000644',
                   'ogrn': '311353817900029',
                   'phone': '+7(953)519-40-34',
                   'email': 'info@lumen35.ru'}

    name = models.CharField(verbose_name=u'Наименование', max_length=250, default=defaultDict['name'])
    street = models.CharField(verbose_name=u'Адресс', max_length=255, default=defaultDict['street'])
    phone = models.CharField(verbose_name=u'Телефон', blank=True, max_length=16, default=defaultDict['phone'])
    email = models.EmailField(verbose_name=u'Электронная почта', default=defaultDict['email'])
    isActive = models.BooleanField(verbose_name=u'Активно', default=True,)

    class Meta:
        db_table = 'contacts'
        ordering = ['name']
        verbose_name = u'Контакты'
        verbose_name_plural = u'Контакты'

    def __unicode__(self):
        return self.name

    def __str__(self):
        return self.name

class price(models.Model):
    name = models.CharField(verbose_name=u'Наименование', max_length=50, default=u'Оптовый прайс')
    price = models.FileField(verbose_name=u'Прайс', upload_to='prices')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=u'Дата создания')
    update_at = models.DateTimeField(auto_now=True, verbose_name=u'Дата обновления')

    class Meta:
        db_table = 'prices'
        ordering = ['name']
        verbose_name = u'Прайс'
        verbose_name_plural = u'Прайс'

    def __unicode__(self):
        return self.price.name

    def __str__(self):
        return self.price.name

class slider(models.Model):
    name = models.CharField(verbose_name=u'Наименование', max_length=255)
    image = models.ImageField(verbose_name=u'Изображение для слайдера', upload_to='images/slider/')
    url = models.URLField(verbose_name=u'Ссылка')
    isActive = models.BooleanField(verbose_name=u'Активно', default=True)

    class Meta:
        db_table = 'slider'
        ordering = ['name']
        verbose_name = u'Слайдер'
        verbose_name_plural = u'Слайдер'

    def __unicode__(self):
        return self.name

    def __str__(self):
        return self.name

class mainPageModel(models.Model):
    name = models.CharField(verbose_name=u'Заголовок', max_length=250)
    content = HTMLField(verbose_name=u'Контент')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    isActive = models.BooleanField(verbose_name=u'Активно', default=True)

    class Meta:
        db_table = 'mainpage'
        ordering = ['-created_at']
        verbose_name = u'Контент главной'
        verbose_name_plural = u'Контент главной'

    def __unicode__(self):
        return self.name

    def __str__(self):
        return self.name

class certificate(models.Model):
    name = models.CharField(verbose_name=u'Наименование', max_length=150)

    class Meta:
        db_table = 'certificates'
        verbose_name = u'Сертификат'
        verbose_name_plural = u'Сертификаты'

    def __unicode__(self):
        return self.name

    def __str__(self):
        return self.name

class imageCertificate(models.Model):
    toCerteficate = models.ForeignKey(certificate, verbose_name=u'Наименование', related_name='image_certificate')
    image = models.ImageField(upload_to='images/certificate/', verbose_name=u"Изображение")

    class Meta:
        db_table = 'images certificates'
        verbose_name = u'Изображение'
        verbose_name_plural = u'Изображения'

    def __unicode__(self):
        return str(self.id)

    def __str__(self):
        return str(self.id)


class globalSEO(models.Model):
    site_name = models.CharField(verbose_name=u'Заголовок сайта', max_length=250)
    meta_keyword = models.TextField(verbose_name=u'Keyword', blank=True)
    meta_description = models.TextField(verbose_name=u'Description', blank=True)

    class Meta:
        db_table = 'SEOS'
        verbose_name = u'Глобальные настройки SEO'
        verbose_name_plural = u'Глобальные настройки SEO'

    def __unicode__(self):
        return self.site_name

    def __str__(self):
        return self.site_name

sender/models.py
# -*- coding: utf-8 -*-
from django.db import models

class senderModel(models.Model):
    name = models.CharField(max_length=60, verbose_name='Имя')
    telephone = models.CharField(max_length=15, verbose_name='Телефон')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    is_sended = models.BooleanField(default=False, verbose_name='Уведомление отправлено')
    info = models.TextField(verbose_name=u'Дополнительная информация', blank=True)

    class Meta:
        db_table='feedback'
        verbose_name='Заявки'
        verbose_name_plural='Заявки'

    def __unicode__(self):
        return self.name

    def __str__(self):
        return self.name

main/forms.py
#-*- coding: utf-8 -*-
from django import forms
from main.models import contactsModel

#не используется
class contactsForm(forms.ModelForm):
    class Meta:
        model = contactsModel
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(contactsForm, self).__init__(*args, **kwargs)
        self.fields['inn'].widget.attrs['style'] = 'width:20em;'
        self.fields['bic'].widget.attrs['style'] = 'width:20em;'
        self.fields['ogrn'].widget.attrs['style'] = 'width:20em;'
        self.fields['rs'].widget.attrs['style'] = 'width:20em;'
        self.fields['ks'].widget.attrs['style'] = 'width:20em;'

main/views.py
# -*- coding: utf-8 -*-
import os
from unidecode import unidecode
from svet_vlad.settings import MEDIA_ROOT
from main.models import price
from main.models import slider
from main.models import mainPageModel
from main.models import certificate

from django.core import urlresolvers
from django.shortcuts import render
from django.shortcuts import HttpResponse
from django.http import HttpResponseRedirect
from django.core.paginator import EmptyPage
from django.core.paginator import Paginator
from django.core.paginator import PageNotAnInteger

def mainPage(request, template_name):
    page_name = u'Главная'
    allContent = mainPageModel.objects.filter(isActive=True)

    paginator = Paginator(allContent, 16)
    page = request.GET.get('page')
    try:
        contents = paginator.page(page)
    except PageNotAnInteger:
        contents = paginator.page(1)
    except EmptyPage:
        contents = paginator.page(paginator.num_pages)

    slides = slider.objects.filter(isActive=True)
    return render(request, template_name, locals())

def download_price(request):
    if request.user.is_authenticated():
        downloadPrice = price.objects.get(name__icontains=u'Оптовый прайс').price
        file_path = u'%s/%s' % (MEDIA_ROOT, downloadPrice.name)
        filename = unidecode(os.path.basename(file_path))
        with open(file_path, 'rb') as fh:
            response = HttpResponse(fh.read(), content_type="application/vnd.ms-excel")
            response['Content-Disposition'] = u'attachment; filename=%s' % (filename)
            return response
    else:
        redirectUrl = urlresolvers.reverse('main')
        return HttpResponseRedirect(redirectUrl)

def certificatesPage(request, template_name):
    cert = certificate.objects.all()[0]
    page_name = cert.name
    return render(request, template_name, locals())

templates/base.html
<!DOCTYPE html>
{%load staticfiles%}

<html class="no-js" lang="ru">
    <head>
        <!--    править meta -->
        <meta name="viewport" content="width=1200" />
        <meta property="og:title" content="{%if page_title%}{{page_title}}{% else %}{{site_name}}{%endif%}" />
        <meta property="og:description" content="{% if globalSeo %}{{ globalSeo.meta_description|striptags  }}{% endif %}" />

        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

        <link rel="stylesheet" type="text/css" href="{% static 'css/foundation.min.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/foundation-icons.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />

        <link rel="shortcut icon" href="{%static 'images/favicon.ico'%}" type="image/x-icon" />

        <title>
            {%block title%}
                {%if page_title%}
                        {{page_title}} |
                {%endif%}
                {{site_name}}
            {%endblock%}
        </title>
        {% if globalSeo %}
            <meta name="keywords" content = "{{ globalSeo.meta_keyword }}" />
            <meta name="discription" content = "{{ globalSeo.meta_description }}" />
        {% endif %}
    </head>
<body>

<div class="off-canvas-wrapper">
    <div class="off-canvas-wrapper-inner" data-off-canvas-wrapper>

      <div class="off-canvas position-left" id="offCanvas" data-off-canvas>

          <button class="close-button" aria-label="Close menu" type="button" data-close>
            <span aria-hidden="true">&times;</span>
          </button>

          <ul class="vertical menu">
              <li class="title-canvas">{{site_name}}</li>

           </ul>

           <ul class="vertical menu">
              <li class="title-canvas">Информация</li>
              <li><a href="/contacts/">Контакты</a></li>
               <li><a href="/about/">О нас</a></li>
               <li><a href="/pay/">Как купить</a></li>
               <li><a href="/partners/">Партнеры</a></li>
           </ul>

      </div>
      <div class="off-canvas-content" data-off-canvas-content>
          <div class="main-section">
            <div class="title-bar show-for-small-only" >
                <div class="title-bar-left">
                    <button class="menu-icon" type="button" data-open="offCanvas"></button>
                </div>
                <div class="title-bar-right">
                    {%if not user.is_authenticated%}
                        <button type="button" data-toggle="modalLogin" onclick="resetAlert()"><i class="fi-torso"></i></button>
                    {% else %}
                        <a href=""><i class="fi-torso"></i></a>
                    {% endif %}
                </div>
            </div>

              {% block header %} {% endblock %}
              {% block content %} {% endblock %}
          </div>
          <div class="footer-section">
              {%block footer%} {%endblock%}
          </div>
      </div>
    </div>
</div>

<div class="tiny reveal" id="callModal" data-reveal>
    <div class="large-12 columns large-inside pop-up">
    <div class="h1">Заказать звонок</div>
    <form class="callback_form">{%csrf_token%}
        {% if getProduct %}
            <input id="id_info" name="info" type="hidden" value="{{ getProduct.slug }}">
        {% endif %}
        <div class="row-form">
            <div class="span1">Имя</div>
            <div class="span2">
                {{ form.name }}
            </div>
            <div class="clear"></div>
        </div>
        <div class="row-form">
            <div class="span1">Телефон</div>
            <div class="span2">
                {{ form.telephone }}
            </div>
        </div>

		<div class="submit">
			<button name="send_button" class="btn_buy popdef">Заказать</button>
		</div>
	</form>
    </div>
    <button class="close-button" data-close aria-label="Close reveal" type="button">
        <span aria-hidden="true">&times;</span>
    </button>
</div>

<div class="tiny reveal" id="loginModal" data-reveal>
     <ul class="tabs pop-up" data-tabs id="login-tabs">
         <div class="large-6 columns large-inside">
             <li class="tabs-title is-active"><a href="#panel1" aria-selected="true">Вход</a></li>
         </div>
         <div class="large-6 columns large-inside">
             <li class="tabs-title"><a href="#panel2">Регистрация</a></li>
         </div>
     </ul>

    <div class="tabs-content" data-tabs-content="login-tabs">
        <div class="tabs-panel is-active" id="panel1">
            <form method="POST" id="login-form">
                {%csrf_token%}
                <div class="large-12">
                    {{ formLogin.email.label_tag }}
                    {{ formLogin.email }}
                    {{ formLogin.password.label_tag }}
                    {{ formLogin.password }}
                    <span id="span-hidden-pw-login" class="span-hidden"></span>
                </div>
                <div class="large-5 large-centered">
                    <button name="login" class="btn_buy popdef">Войти</button>
                </div>
            </form>
        </div>

        <div class="tabs-panel" id="panel2">
            <form method="POST" id="registration-form">
                {% csrf_token %}
                <div class="large-12">
                    {{ formRegister.email.label_tag }}
                    {{ formRegister.email }}
                    <span id="span-hidden-em-reg" class="span-hidden"></span>
                    {{ formRegister.first_name.label_tag }}
                    {{ formRegister.first_name }}
                    {{ formRegister.last_name.label_tag }}
                    {{ formRegister.last_name }}
                    {{ formRegister.phone.label_tag }}
                    {{ formRegister.phone }}
                    {{ formRegister.password1.label_tag }}
                    {{ formRegister.password1 }}
                    <span id="span-hidden-pw-reg" class="span-hidden"></span>
                    {{ formRegister.password2.label_tag }}
                    {{ formRegister.password2 }}
                </div>
                <div class="large-6 large-centered">
                    <button name="registration" class="btn_buy popdef">Регистрация</button>
                </div>
            </form>
        </div>
    </div>

    <button class="close-button" data-close aria-label="Close reveal" type="button">
        <span aria-hidden="true">&times;</span>
    </button>
</div>

<script type="text/javascript" src="{% static 'js/vendor/jquery.js' %}"></script>
<script type="text/javascript" src="{% static 'js/vendor/foundation.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/vendor/imagelightbox.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/main-svet.js' %}"></script>

</body>
</html>

templates/main.html
{%extends 'base.html'%}
{%load staticfiles%}
{%load thumbnail%}

{% block header %}
    <header id="header">
        <div class="row">
            <div class="large-12 columns" id="header-top">
                    <div class="large-3 columns">
                        <a href="/" class="logo"></a>
                    </div>
                    <div class="large-3 large-offset-2 columns">
                        <div id="free-telefonia" class="phone">{{ contacts.phone }}</div>
                    </div>
                    <div class="large-2 columns">
                        <p class="time">
                            <i class="fi-clock"></i>Время работы:
                        </p>
                        <p>
                            ПН-ПТ 08:00 - 17:00<br>
	                        СБ-ВС выходные дни
                        </p>
                    </div>
                    <div class="large-2 columns">
                        {%if user.is_authenticated%}
                            <a href="{% url 'logout' %}" class="button btn-header">
                                <span class="text">Выход</span>
                            </a>
                        {% else %}
                            <a class="button btn-header" data-toggle="loginModal">
                                <span class="text">Вход</span>
                            </a>
                        {% endif %}
                         <a class="button btn-header" data-toggle="callModal">
                            <span class="text">Заказать звонок</span>
                        </a>
                    </div>

            </div>
        </div>
        <div class="row">
            <div class="large-12 columns">
                <div class="top-menu">
                    <ul class="store-horizontal">
                        <li>
                            <a href="{% url 'catalog' %}" class="root-item">Каталог товаров</a>
                        </li>
                        <li>
                            <a href="/partner/" class="root-item">Сотрудничество</a>
                        </li>
                        <li>
                            <a href="{% url 'ourworks' %}" class="root-item">Наши работы</a>
                        </li>
                        <li>
                            <a href="{% url 'blog' %}" class="root-item">Наш блог</a>
                        </li>
                        <li>
                            <a href="/contacts/" class="root-item">Контакты</a>
                        </li>
                        <li>
                            <a href="/certificate/" class="root-item">Сертификаты</a>
                        </li>
                        {%if user.is_authenticated%}
                            <li>
                                <a href="{% url 'download_price' %}" class="root-item">Прайс-лист</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="large-12 columns large-inside">
                <div class="wrap3d">
                    <div class="compo3d">
                        <div id="light_profil"></div>
                        <div id="light_projectors"></div>
                        <div id="light_lamps"></div>
                        <div id="light_rgb"></div>
                        <div id="light_linear"></div>
                        <div id="light_pointers"></div>
                        <div id="light_ribbon"></div>
                    </div>
                </div>
            </div>
        </div>

    </header>
{% endblock %}

{%block content%}
    <div class="row">
        <div class="large-12 columns" id="content-wrap">
            <div class="large-3 columns">
                {% if getCatalog %}
                    {% include 'tags/vertical-nav.html' %}
                {% endif %}
            </div>
            <div class="large-9 columns">
                {% if slides %}
                    <div class="orbit" role="region" data-orbit {% if slides.count < 2 %}data-auto-play="false"{% endif %}>
                    <button class="orbit-previous"><span class="show-for-sr">Previous Slide</span>&#9664;&#xFE0E;</button>
                    <button class="orbit-next"><span class="show-for-sr">Next Slide</span>&#9654;&#xFE0E;</button>

                        <ul class="orbit-container">
                            {% if slides.count > 1 %}
                                {% for slider in slides %}
                                    <li class="orbit-slide">
                                        <a href="{{ slider.url }}">
                                            {% thumbnail slider.image "600x210" crop="center" as im %}
                                                <img class="orbit-image" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
                                            {% endthumbnail %}
                                        </a>
                                    </li>
                                {% endfor %}
                            {% else %}
                                <li class="orbit-slide">
                                    <a href="{{ slider.url }}">
                                        {% thumbnail slider.0.image "600x210" crop="center" as im %}
                                            <img class="orbit-image" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt='{{ slider.0.name }}'>
                                        {% endthumbnail %}
                                    </a>
                                </li>
                            {% endif %}
                        </ul>
                    </div>
                {% endif %}
            </div>
            {% if contents %}
            <div class="large-9 columns">
                {% for content in contents%}
                    <div class="large-12 columns large-inside">
                        <div class="main-content-field">
                            {{ content.content|safe }}
                        </div>
                        <hr>
                    </div>
                {% endfor %}

                {% if allContent.count > 16 %}
                    <div class="large-12 columns large-inside">
                        <ul class="pagination" role="navigation" aria-label="Pagination">
                            {% if contents.has_previous %}
                                <li class="pagination-previous"><a href="?page={{contents.previous_page_number}}"><span class="show-for-sr">page</span></a></li>
                            {% endif %}
                            {%for page in contents.paginator.page_range%}
                                {%if page == products.number%}
                                    <li class="current"><a href="?page={{page}}">{{page}}</a></li>
                                {%else%}
                                    <li><a href="?page={{page}}">{{page}}</a></li>
                                {%endif%}
                            {%endfor%}

                            {% if contents.has_next %}
                                <li class="pagination-next"><a href="?page={{contents.next_page_number}}"><span class="show-for-sr">page</span></a></li>
                            {% endif %}
                        </ul>
                    </div>
                {% endif %}
            </div>
            {% endif %}
        </div>
    </div>
{%endblock%}

{% block footer %}
    <div class="row">
        <div class="large-4 columns">
            <div class="footer-logo">
                <a href="{% url 'main' %}"></a>
            </div>
                <address class="adress">
                    <span class="date-site">2010-2017 - «lumen35.ru» © Свет в будущее</span>
                    <span class="date-site">{{ contacts.street }}</span>
                </address>

        </div>
        <div class="large-4 large-offset-4 columns">
            <div class="contacts-two">
                <span class="contacts-footer">Контактные данные: {{ contacts.phone }}</span>
                <span class="contacts-footer">email: {{ contacts.email }}</span>
            </div>
        </div>
         <div class="large-4 large-offset-4 columns">
             <div class="contacts-btn">
                <a class="button btn-footer" data-toggle="callModal">
                    <span class="text">Заказать звонок</span>
                </a>
            </div>
        </div>
        <div class="large-12 columns">
            <div class="copy">Информация на сайте lumen35.ru не является публичной офертой. Указанные цены действуют только при оформлении заказа через интернет-магазин lumen35.ru.</div>
        </div>
    </div>
{% endblock %}